name: 'Sync Cloudflare Pages'
description: 'Syncs cloudflare.json configuration to Cloudflare Pages with GitHub integration'
author: 'alexcarol'

inputs:
  cloudflare-api-token:
    description: 'Cloudflare API token with Pages permissions'
    required: true
  cloudflare-account-id:
    description: 'Cloudflare Account ID'
    required: true
  config-path:
    description: 'Path to cloudflare.json config file'
    required: false
    default: 'cloudflare.json'
  allow-recreate:
    description: 'Allow deleting and recreating Direct Upload projects for GitHub migration'
    required: false
    default: 'false'

runs:
  using: 'composite'
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '24'

    - name: Install dependencies
      shell: bash
      run: npm install
      working-directory: ${{ github.action_path }}

    - name: Sync Cloudflare configuration
      shell: bash
      env:
        CLOUDFLARE_API_TOKEN: ${{ inputs.cloudflare-api-token }}
        CLOUDFLARE_ACCOUNT_ID: ${{ inputs.cloudflare-account-id }}
        CONFIG_PATH: ${{ github.workspace }}/${{ inputs.config-path }}
        ALLOW_RECREATE: ${{ inputs.allow-recreate }}
      run: node ${{ github.action_path }}/sync-cloudflare.mjs

branding:
  icon: 'cloud'
  color: 'orange'
